### ISSUE TITLE
Login / Register Screen

### ISSUE THREAD

**Issue by jessevdp** [team-avans-p/catan#2]
When launching the application the user should first be requested to login. This will be a separate screen. If the user doesn't have an account yet they can register. An account will consist of just a username and a password.

**Comment by jessevdp** [comment]
Branch name should be `feature/login-register-screen` or something like that.

**Comment by Martijnpold** [comment]
If I be can honest mostly then the description given can be gooder @jessevdp

**Comment by jessevdp** [comment]
@Kemyx do you have any insights on the design?

**Comment by yymar** [comment]
@Martijnpold 🔥 remove LoginPanel from AKD, because it's no longer needed.
